<?php

declare(strict_types=1);
require_once __DIR__ . '/../bootstrap.php';
/*
First step here is to require this auto loading file generated by composer.
By including this file, I'm giving my app auto loading functionality automatically generated and handled

Now I can use classes from different namespaces.This is how you tell PHP.
It should load some class by just using a namespace or using a class from a namespace.
*/
require_once __DIR__ . '/../vendor/autoload.php';

use Core\Router;

$router = new Router();
require_once __DIR__ . '/../routes.php';

$uri = parse_url($_SERVER['REQUEST_URI'])['path'];
$method = $_SERVER['REQUEST_METHOD'];
echo $router->dispatch($uri, $method);